### ISSUE TITLE
大文件报错

### ISSUE THREAD

**Issue by YIZXIY** [kslz/sound_dataset_tools2#1]
提示不支持超过4GB的文件，请问应如何解除这一限制

**Comment by kslz** [comment]
这是pydub的限制，因为触及到了python的极限。。。
我这有条命令 能将文件裁切成3600秒（即一小时）一段的短音频，你可以先将大音频文件切成小段，再尝试导入
`ffmpeg -i input.wav -f segment -segment_time 3600 -c copy output_%03d.wav`
input.wav为你的长音频文件，3600为输出音频段的秒数
输出的音频将以output001.wav/output002.wav...... 这样的格式命名

**Comment by YIZXIY** [comment]
> 这是pydub的限制，因为触及到了python的极限。。。 我这有条命令 能将文件裁切成3600秒（即一小时）一段的短音频，你可以先将大音频文件切成小段，再尝试导入 `ffmpeg -i input.wav -f segment -segment_time 3600 -c copy output_%03d.wav` input.wav为你的长音频文件，3600为输出音频段的秒数 输出的音频将以output001.wav/output002.wav...... 这样的格式命名

苦逼的我 独自面对这70h的素材思考人生
