### ISSUE TITLE
用v0.0.4版本 双击exe闪退

### ISSUE THREAD

**Issue by kirbystudy** [kslz/sound_dataset_tools2#2]

**Comment by kslz** [comment]
在文件资源管理器的地址栏中输入cmd 然后在打开的cmd中输入main.txt 看看结果

**Comment by kslz** [comment]
在文件资源管理器的地址栏中输入cmd 然后在打开的cmd中输入main.exe 看看结果

**Comment by kirbystudy** [comment]
![image](https://user-images.githubusercontent.com/63231787/225175079-fe5a94c4-e7dd-4322-838c-012a1aa32de0.png)

**Comment by kslz** [comment]
改回原来的编译方式了 你再重下载看下

**Comment by kirbystudy** [comment]
现在的版本运行没报错了

**Comment by kirbystudy** [comment]
还有一个问题，就是为什么我导入的音频和视频上的不是分割的字幕，都是连贯的。
![image](https://user-images.githubusercontent.com/63231787/225179325-51c6c615-9801-4cd8-a6e6-b90f24c94f38.png)

**Comment by kslz** [comment]
你的电脑装过python和visual studio吗？我想判断一下编译报错的原因

**Comment by kslz** [comment]
> 还有一个问题，就是为什么我导入的音频和视频上的不是分割的字幕，都是连贯的。 ![image](https://user-images.githubusercontent.com/63231787/225179325-51c6c615-9801-4cd8-a6e6-b90f24c94f38.png)

截图看一下你的字幕文件的前几条

**Comment by kirbystudy** [comment]
![image](https://user-images.githubusercontent.com/63231787/225179583-f7770cc6-e5fd-42a3-8a26-74a6bc437c82.png)

**Comment by kslz** [comment]
我知道原因了。。。程序会把过于相近的两条字幕练起来视作一条，不知为何你的字幕都是首尾相连的，我再改下
另外你的字幕是怎么来的 是某个软件识别的吗

**Comment by kirbystudy** [comment]
字幕是whisper识别的

**Comment by kirbystudy** [comment]
你的电脑装过python和visual studio吗？我想判断一下编译报错的原因
-----------------------------------------------------------------------------
我本地没py环境，我可以叫其他小伙伴帮忙，他也是window系统。

**Comment by kslz** [comment]
> 字幕是whisper识别的

又提了一版 你再下载看看，另外据我的尝试，whisper识别的字幕时间是不准的，我用medium试很不准，large不清楚，如果可以的话还是建议用剪映

**Comment by kslz** [comment]
> ## 你的电脑装过python和visual studio吗？我想判断一下编译报错的原因
> 我本地没py环境，我可以叫其他小伙伴帮忙，他也是window系统。

了解了 现在不用，我还在上班，之后有空了再研究一下

**Comment by kirbystudy** [comment]
我看过了，字幕都是对的上的，我用potplayer

**Comment by kslz** [comment]
> 我看过了，字幕都是对的上的，我用potplayer

好吧，用的large模型？

**Comment by kirbystudy** [comment]
用的medium, 素材是很清晰的

**Comment by kirbystudy** [comment]
提取人声后再识别字幕会比较好

**Comment by kslz** [comment]
> 用的medium, 素材是很清晰的

嗯...我再试一下吧 正好到货了新显卡...

**Comment by kirbystudy** [comment]
请问大佬加了这个功能了吗

**Comment by kslz** [comment]
> 请问大佬加了这个功能了吗

忘了说，目前是可选是否自动合并过近字幕了  试试0.0.4版本吧

**Comment by kirbystudy** [comment]
好的谢谢。

**Comment by kirbystudy** [comment]
能不能加一个单个音频下载的功能

**Comment by kirbystudy** [comment]
就是切割之后的音频

**Comment by kslz** [comment]
> 就是切割之后的音频

应该行，我之后加一下

**Comment by kslz** [comment]
> 就是切割之后的音频

更新上了 再有问题开新issue吧
