### ISSUE TITLE
关于自动优化逻辑

### ISSUE THREAD

**Issue by TinaChen95** [kslz/sound_dataset_tools2#5]
请问您说的“断音”、“自动优化”，指的是不是字幕文件时间戳不准确，导致切割不准确的问题呀？

**Comment by kslz** [comment]
> 请问您说的“断音”、“自动优化”，指的是不是字幕文件时间戳不准确，导致切割不准确的问题呀？

对，就是在起始端向前找响度的低谷，在结尾端向后找响度的低谷，画了个图，差不多是这个意思
![新建项目 (32)](https://user-images.githubusercontent.com/54951765/233830092-613c483f-9939-4a5c-b127-147867ef95f2.png)

**Comment by TinaChen95** [comment]
图片解释的很清楚，谢谢！
